name: tabular-tndp
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy
  - pandas
  - matplotlib
  - pygame
  - pyyaml
  - wandb
  - gymnasium
  - pip
  - pip:
    - mo-gymnasium
    - codecarbon
    - -e ./envs/mo-tndp
